### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'connect')

### ISSUE THREAD

**Issue by manhhuycao** [mashharuki/AptosRepo#1]
Hi @mashharuki 

i have a problem with promise window.aptos.connect(); --> Error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'connect')

This's my code

![image](https://user-images.githubusercontent.com/40655080/196918213-61f821f1-b9b3-49f4-a30d-75102e958336.png)

So happy if you can help me find the bug.
Thank you.

**Comment by mashharuki** [comment]
@manhhuycao  Thank you for commenting!!

I saw your code.

Do you write below code in `index.tsx` file??

```ts
declare global {
  interface Window { aptos: any; }
}
```

**Comment by mashharuki** [comment]
@manhhuycao 

My  full `index.tsx` flie is here.

```ts:index.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import './css/index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

declare global {
  interface Window { aptos: any; }
}

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);

window.addEventListener('load', () => {
  root.render(
    <React.StrictMode>
      <App />
    </React.StrictMode>
  );
});

reportWebVitals();
```

**Comment by mashharuki** [comment]
@manhhuycao Thank you!! Um........

**Comment by mashharuki** [comment]
@manhhuycao I think your code is correct.

**Comment by manhhuycao** [comment]
i fixed it.
because i use pontem wallet so i change "window.pontem.account();" , it work

**Comment by mashharuki** [comment]
@manhhuycao Congratulation!!!

**Comment by mashharuki** [comment]
@manhhuycao I use Petra wallet.
